package com.project.mytelevet.common;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.widget.TextView;

import com.project.mytelevet.R;

public class TCActivity extends AppCompatActivity {
    TextView tc;

    @SuppressLint("SetTextI18n")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_t_c);
        tc = findViewById(R.id.textView_tc);
        tc.setText("PLATFORM TERMS OF USE\n" +
                "\n" +
                "PLEASE READ THE FOLLOWING CAREFULLY.  THIS IS A LEGALLY BINDING AGREEMENT BETWEEN YOU AS AN END USER (AS DEFINED BELOW) (“END USER” OR “YOU”) AND MY VIRTUAL VET, INC. (“MY VIRTUAL VET, INC.” OR “WE”).  THIS PLATFORM TERMS OF USE AGREEMENT, TOGETHER WITH ALL AMENDMENTS, AND COLLECTIVELY WITH ALL MY VIRTUAL VET, INC. RULES AND POLICIES, INCLUDING THE MY VIRTUAL VET, INC. PRIVACY POLICY, CONSTITUTE THE “AGREEMENT” BETWEEN YOU AND MY VIRTUAL VET, INC. REGARDING YOUR ACCESS TO AND USE OF THE MY VIRTUAL VET, INC. PLATFORM (“PLATFORM”).  BY ACCESSING OR USING THE PLATFORM, YOU SIGNIFY THAT YOU HAVE READ THE AGREEMENT AND THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY THE AGREEMENT.\n" +
                "IF YOU HAVE NOT READ THE AGREEMENT, DO NOT UNDERSTAND OR AGREE TO BE BOUND BY THE AGREEMENT, OR ARE NOT ABLE TO CONSENT TO BE BOUND BY THE AGREEMENT (E.G., IF YOU ARE NOT OLD ENOUGH TO ENTER INTO A BINDING LEGAL CONTRACT), DO NOT USE OUR PLATFORM.\n" +
                "\n" +
                "1.    Scope and Acceptance\n" +
                "Anyone who accesses or uses our  Platform is an “End User.”  The Agreement sets forth your rights and obligations as an End User with respect to your access to and use of the Platform and use of any and all information or data of any kind arising from access to, or use of, the Platform, including, without limitation, any text, graphics, images, art work, sound recordings, audio, video, and software.\n" +
                "We reserve the right, in our sole discretion, to change this Agreement (including the Privacy Policy) from time to time, without prior notice.  You are responsible for reviewing the Agreement regularly.  Your access to any part of the Platform is deemed to be your acceptance of this Agreement, and any changes thereto.\n" +
                "If you are accessing or using any part of the Platform on behalf of any business, organization, or other entity of any kind, you represent and warrant that you are authorized (a) to accept these terms on its behalf and (b) to bind such business, organization, or entity to the Agreement.\n" +
                "\n" +
                "2.    Privacy Policy\n" +
                " Please see our Privacy Policy for a detailed description of how we collect, use, and disclose information about our End Users.\n" +
                "\n" +
                "3.    Description of Platform\n" +
                "THE SITE, APPLICATION, AND SERVICES COMPRISE AN ONLINE PLATFORM THROUGH WHICH PET OWNERS MAY CONNECT WITH VETERINARIANS ABOUT A PET’S HEALTHCARE, GENERAL QUESTIONS, OR QUESTIONS PERTAINING TO THE ANIMAL. YOU UNDERSTAND AND AGREE THAT MY VIRTUAL VET, INC. IS NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN VETERINARIANS AND GUESTS, NOR IS MY VIRTUAL VET, INC. PRACTICING OR ADMINISTERING ANY DIAGNOSIS, TREATMENTS, OR HEALTHCARE SUGGESTIONS AND DISCLAIMS ALL LIABILITY IN THIS REGARD TO THE MAXIMUM EXTENT PERMITTED BY LAW.\n" +
                "PRIOR TO USING THESE SERVICES YOU ASSERT THAT A VETERINARY-CLIENT-PATIENT-RELATIONSHIP (VCPR) EXISTS WITH THE VETERINARIAN AND PET YOU HAVE CONNECTED OR, IN THE ABSENCE OF VCPR, YOU ARE ONLY SEEKING VETERINARY ADVICE AND NOT A DIAGNOSIS, TREATMENT, OR PRESCRIPTION MEDICATION.\n" +
                "\n" +
                "4.    Informed Consent\n" +
                "A. Telehealth is the delivery of health care services using interactive audio and video technology, where the patient and the veterinary professional are not in the same physical location.\n" +
                "B. The telehealth Services you receive from your veterinarian are not intended to replace a veterinary client patient relationship or be your permanent medical home. As with any online health service, there are potential risks associated with use. When using this service, you understand the additional risks of telehealth and waive any liability to Company or Veterinarian. These risks include but may not be limited to: In rare cases, information transmitted may not be sufficient (e.g. poor resolution of images) to allow for appropriate health care decision making by the Veterinarian; Delays in evaluation or treatment could occur due to failures of the electronic equipment or clinic staffing; lack of access to all of your health records may result in adverse drug interactions or allergic reactions or other judgment errors; an incomplete or inaccurate diagnosis of pet. If your pet is experiencing an emergency, you should visit an emergency room or call your primary veterinary clinic immediately. It is not recommended to use our Service when your pet is having an emergency.\n" +
                "C. By accepting these Terms of Use, you acknowledge that you understand and agree with the following: you may expect the anticipated benefits from the use of telehealth, but that no results can be guaranteed or assured. In some instances, your veterinarian may determine that the Services are not appropriate for some or all of your pet’s treatment needs, and accordingly may elect not to provide telehealth services to you. In the event an in-office visit is requested, your veterinarian may charge you for services rendered through My Virtual Vet, Inc.\n" +
                "D. You may also be able to send written notes to your veterinarian by creating a “Chat Only” appointment through the Platform. You should not rely on a “Chat Only” appointment if you need immediate attention from a Treating Provider or other health care professional. If your pet is experiencing a medical emergency, you should contact the nearest emergency clinic. You understand and agree that messaging with veterinarians over a “Chat Only” appointment does not give rise to a provider-patient relationship, and does not by itself constitute treatment, diagnosis, or medical advice.\n" +
                "\n" +
                "5.    Operation\n" +
                "The specific features and functionality of the Platform are dynamic and may change from time to time.  We reserve complete discretion with respect to the operation of the Platform.  We also reserve the right to withdraw, suspend, or discontinue any functionality or feature of the Platform at any time.\n" +
                "\n" +
                "6.    Inaccuracies\n" +
                "We make great efforts to provide accurate information on the Platform.  However, we disclaim—and you release us from any liability regarding—errors, inaccuracies, and omissions of the Platform.  We reserve the right to correct any errors, inaccuracies, or omissions and to change or update information at any time without prior notice.  My Virtual Vet, Inc. makes no guarantees whatsoever as to the completeness, timeliness, correctness, or accuracy of the materials or data available through the Platform.  If you believe any portion of the Platform includes an error or inaccuracy, please notify us.\n" +
                "\n" +
                "7.    Permitted Use\n" +
                "Certain My Virtual Vet, Inc. materials provided through the Platform are protected by intellectual property laws, including but not limited to U.S. copyright laws.  You expressly acknowledge and agree that the content accessible through the Platform that is not expressly designated as being provided by another End User is the property of My Virtual Vet, Inc. and its content providers, and My Virtual Vet, Inc. and its content providers retain all right, title, and interest in the content. Subject to the terms of this Agreement, you are granted a limited, personal, non-exclusive, non-sublicensable, non-assignable, non-transferable, and revocable license to access and use the Platform and related materials solely for your own non-commercial use.  Except as expressly provided, all rights are reserved.  Nothing contained in this Agreement or on the Platform shall be construed as conferring by implication, estoppels or otherwise any license or right under any patent or trademark of My Virtual Vet, Inc., or any third party. Except as expressly permitted by the Agreement, in connection with the use of the Platform, you may not:\n" +
                "(a)    alter or modify the Platform, or make any electronic reproduction, adaptation, distribution, performance, or display of the Platform, or any portion thereof, except to the extent required for the limited purpose of reviewing material on the Platform; or\n" +
                "(b)    sell, rent, lease, transfer, distribute, broadcast, display, provide, or otherwise assign to any third party any rights to the Platform, or related materials; or\n" +
                "(c)    remove or modify any proprietary notice or labels on the Platform, or related materials, including author attribution and copyright notices, or use any of our trademarks as meta-tags on any other Platform; or\n" +
                "(d)    use the Platform for any non-authorized purpose or any illegal purpose; or\n" +
                "(e)    copy, modify, erase, or damage any information contained on computer servers used or controlled by My Virtual Vet, Inc. or any third party; or\n" +
                "(f)    use the Platform to violate any legal right of any third party, including any publicity or privacy right, copyright, or other intellectual property right, or to take any action that is harassing, libelous, defamatory, abusive, tortious, threatening, harmful, or otherwise objectionable; or\n" +
                "(g)    access or use any password-protected, secure, or non-public areas of the Platform, or access data on the Platform not intended for you, except as specifically authorized by My Virtual Vet, Inc.; or\n" +
                "(h)    impersonate or misrepresent your affiliation with any person or entity; or\n" +
                "(i)    use any automated means to access or use the Platform, including scripts, bots, scrapers, data miners, or similar software, or display the Platform, or portions thereof, in things (e.g., framing, scraping, etc.), without our express written permission; or\n" +
                "(j)    attempt to or actually disrupt, impair, or interfere with the Platform, or any information, data, or materials posted and/or displayed by My Virtual Vet, Inc.; or\n" +
                "(k)    attempt to probe, scan, or test the vulnerability of the Platform or breach any implemented security or authentication measures, regardless of your motives or intent; or\n" +
                "(l)    attempt to interfere with or disrupt access to or use of the Platform by any user, processor, host, or network, including, without limitation, by submitting a virus, worm, Trojan horse, or other malicious code.\n" +
                "\n" +
                "8.    Third Party Properties Referred to on the Platform\n" +
                " Our Platform may refer to physical venues, geographical sites, Platforms on the Internet, and/or products or services that are not under the control of or maintained by My Virtual Vet, Inc. (“Third Party Properties”).  Unless expressly stated to the contrary, such references do not constitute an affiliation with or endorsement by My Virtual Vet, Inc. of any such Third Party Properties.  You acknowledge that My Virtual Vet, Inc. is providing any references to such Third Party Properties to you solely as a convenience to you, and you agree that My Virtual Vet, Inc. is not responsible for any injury, harm, damages, or negative experience you may encounter by accessing, visiting, or using such Third Party Properties.  My Virtual Vet, Inc. does not endorse or make any representations about any Third Party Properties.  If you access, visit, or use any Third Party Properties referred to on our Platform, you do so at your own risk.\n" +
                "\n" +
                "9.    Availability of the Platform\n" +
                "It is not possible to operate our Platform with 100% guaranteed uptime.  My Virtual Vet, Inc. will make reasonable efforts to keep our Platform operational. However, certain technical difficulties, routine site maintenance and upgrades, and other events may, from time to time, result in interruptions to or outages of our Platform.  You agree that My Virtual Vet, Inc. shall not be liable to you or to any third party for any direct or indirect consequence of any modification, suspension, discontinuance of, or interruption to our Platform.\n" +
                "\n" +
                "10.    Limitation of Liability and Release\n" +
                "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, IN NO EVENT SHALL MY VIRTUAL VET, INC. OR ANY OF ITS AFFILIATES OR SUPPLIERS (INCLUDING ANY OF ITS OR THEIR PARTNERS, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, SUCCESSORS, OR ASSIGNEES) BE LIABLE TO YOU (INCLUDING ANY OF YOUR PARTNERS, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, SUCCESSORS, OR ASSIGNEES) FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, WHETHER ARISING IN CONTRACT, EQUITY, INTENDED CONDUCT, TORT, OR OTHERWISE (INCLUDING BREACH OF WARRANTY, NEGLIGENCE, AND STRICT LIABILITY IN TORT), NOR FOR ANY DAMAGES ARISING FROM DELAY, LOSS OF GOODWILL, LOSS OF OR DAMAGE TO DATA, INTERRUPTION IN USE OR AVAILABILITY OF DATA, LOSS OF USE OF MONEY OR USE OF PRODUCTS, LOST PROFITS, REVENUE OR SAVINGS (ACTUAL OR ANTICIPATED), OR OTHER ECONOMIC LOSS ENSUING FROM OR IN CONNECTION WITH THE EXISTENCE, ACCESS TO, USE OF, OR INABILITY TO USE THE PLATFORM OR RELATING TO ANY MATERIALS, INFORMATION, QUALIFICATION, OR RECOMMENDATIONS ON THE PLATFORM, EVEN IF MY VIRTUAL VET, INC. OR ANY OF ITS AFFILIATES OR SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING THE FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.\n" +
                "YOU EXPRESSLY WAIVE AND RELEASE ANY AND ALL RIGHTS AND BENEFITS UNDER SECTION 1542 OF THE CIVIL CODE OF THE STATE OF CALIFORNIA (OR ANY ANALOGOUS LAW OF ANY OTHER STATE), WHICH READS AS FOLLOWS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM, MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”\n" +
                "Despite the foregoing limitation of liability for damages, if a court or other tribunal of competent jurisdiction decides to award monetary damages to you for any claim or cause of action arising from the same, the amount of monetary damages for such claim or cause of action shall not exceed one hundred U.S. dollars ($100).\n" +
                "\n" +
                "11.    Indemnity\n" +
                "YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS MY VIRTUAL VET, INC., ITS PARENTS, SUBSIDIARIES, AND AFFILIATES, AND ITS AND THEIR RESPECTIVE DIRECTORS, OFFICERS, PARTNERS, EMPLOYEES, AGENTS, CONTRACTORS, SUCCESSORS, AND ASSIGNS FROM AND AGAINST ALL CLAIMS, DEMANDS, LAWSUITS, DAMAGES, LIABILITIES, LOSSES, COSTS, OR EXPENSES (INCLUDING, BUT NOT LIMITED TO, REASONABLE FEES AND DISBURSEMENTS OF COUNSEL AND COURT COSTS), JUDGMENTS, SETTLEMENTS, AND PENALTIES OF EVERY KIND ARISING FROM OR RELATING TO ANY VIOLATION OF THIS AGREEMENT AND ANY ACTIVITY RELATED TO YOUR USE OF THE PLATFORM OR THE INFORMATION CONTAINED ON THE PLATFORM.\n" +
                "\n" +
                "12.    Termination\n" +
                "You agree that My Virtual Vet, Inc. may, to the extent feasible, in its sole discretion, and without prior notice, terminate your access to or use of any portion of our Platform at any time and for any reason, with or without cause.  You also agree that any violation by you of the Agreement will constitute an unlawful and unfair business practice that will cause irreparable harm to My Virtual Vet, Inc. for which monetary damages would be inadequate.  You consent to My Virtual Vet, Inc.’s obtaining any injunctive or equitable relief that My Virtual Vet, Inc. deems necessary or appropriate in such circumstances, without the need for a bond.  These remedies are in addition to any other remedies My Virtual Vet, Inc. may have at law or in equity.\n" +
                "\n" +
                "13.    Intellectual Property\n" +
                "The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of My Virtual Vet, Inc. and its licensors. Copyright, trademark, and other laws of both the United States and foreign countries protect the Service. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of My Virtual Vet, Inc.\n" +
                "\n" +
                "14.    General\n" +
                "\n" +
                "14.1    Modifications\n" +
                "At any time and in My Virtual Vet, Inc.’s sole discretion, we may add, delete, or modify the Agreement.  We will use commercially reasonable efforts to publish any revised portion of the Agreement, for example, by publishing the latest version of these terms and conditions at this URL.  Should you deem any such addition, deletion, or modification to the Agreement unacceptable, you shall stop accessing and using the Platform.  All changes to the Agreement shall be effective immediately.\n" +
                "\n" +
                "14.2    Access and Use Where Prohibited\n" +
                "Access to and use of our Platform are unauthorized in any jurisdiction that does not give effect to all provisions of the Agreement, including without limitation this provision.\n" +
                "\n" +
                "14.1    Operation of the Platform from the United States of America\n" +
                "By accessing and using the Platform, you acknowledge and agree that My Virtual Vet, Inc. controls and operates all parts of the Platform from its offices in the United States of America and that the Platform, and the information contained on the Platform, is intended for use by End Users located in the United States of America.  Other countries may have laws, regulatory requirements and medical practices that differ from those in the United State of America. Unless expressly stated to the contrary, My Virtual Vet, Inc. makes no representation that the Platform, or the information contained on the Platform, is appropriate or will be available for use in other locations.  Unless otherwise explicitly stated, all material and content found on or accessible through the Platform is solely directed to individuals, companies, or other entities located in the United States of America.  My Virtual Vet, Inc. reserves the right to limit, in its sole discretion, the provision and quantity of any feature, product, or service to any person or geographic area.  Any offer for any feature, product, or service made on or through the Platform is void where prohibited.  If you access or use the Platform from outside the United States of America, you are entirely responsible for compliance with applicable local laws and other applicable laws.  You may not use any portion of the Platform in violation of applicable export laws and regulations.\n" +
                "If you access the Platform from outside the United States, you acknowledge and agree that your information may be transferred to and maintained on computers and servers located outside of your state, province, country, or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction.  Your consent to the Agreement followed by your submission of such information represents your agreement to the transfer of such information to the United States and the collection, use, and disclosure of your information in accordance with United States law and our Privacy Policy.\n" +
                "\n" +
                "14.2    Applicable Law and Venue\n" +
                "Any action related to the Agreement will be governed by the laws of Delaware, without regard to the choice or conflicts of law provisions of any jurisdiction.  You and My Virtual Vet, Inc. agree and consent that jurisdiction, proper venue, and the most convenient forums for all claims, actions, and proceedings of any kind relating to our Platform or the Agreement will be exclusively in the federal or state courts of Delaware.\n" +
                "\n" +
                "14.3    Dispute Resolution\n" +
                "My Virtual Vet, Inc. intends to resolve any and all disputes that may arise between it and its End Users in a cost-effective and non-disruptive manner, preferably without the time and expense of litigation.  Toward this end, you agree to the following dispute resolution procedure.  If you are unable to resolve any dispute in the ordinary course of business, you shall send a written notice to My Virtual Vet, Inc. in which you outline the issues in dispute, enclose any relevant documents, and state the requested relief.  My Virtual Vet, Inc. shall respond within ten (10) business days with identical information from its perspective.  You and a representative of My Virtual Vet, Inc. shall meet or communicate electronically within ten (10) business days of the delivery of the response, and as often as you and My Virtual Vet, Inc. mutually deem necessary or desirable thereafter, in an attempt to resolve the matter.  If, within sixty (60) days of the first communication, you and My Virtual Vet, Inc. fail to resolve the matter, you and My Virtual Vet, Inc. shall seek to mediate the dispute with a neutral third party.  Neither party shall seek further legal action unless such mediation fails to achieve a resolution acceptable to both parties.  You agree that you will not bring or be a party to any class-action lawsuit against My Virtual Vet, Inc.\n" +
                "\n" +
                "14.4    Unsolicited Materials and End User’s Grant of Limited Licensed\n" +
                "In operating our Platform, My Virtual Vet, Inc. does not solicit nor does it wish to receive any confidential, secret or proprietary information or other material from you through the Platform, our mail and e-mail addresses, or in any other way.  Any information or material submitted or sent to My Virtual Vet, Inc. (including, but not limited to, comments, questions, feedback, data, suggestions, ideas and the like) will be deemed to be not confidential or secret. By submitting or sending information or other material to My Virtual Vet, Inc., you represent and warrant that the information is original to you and that no other party has any rights to the material.\n" +
                "By communicating with My Virtual Vet, Inc., including submitting or sending content to us, you grant My Virtual Vet, Inc. the royalty-free, unrestricted, world-wide, perpetual, irrevocable, non-exclusive, and fully sublicensable right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such content (in whole or part), including any information, suggestions, ideas, drawings or concepts contained in such content, worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed. Such license includes incorporating the content, in whole or in part, into a My Virtual Vet, Inc. feature. You will remain responsible for the accuracy, copyright compliance, legality, decency, or any other aspect of such submitted material, including any content or part thereof, or other communication to My Virtual Vet, Inc.  You also warrant that any \"moral rights\" in such content is waived.\n" +
                "\n" +
                "14.5    Miscellaneous\n" +
                "If any part of the Agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Agreement shall continue in effect.\n" +
                "No failure or delay in enforcing any provision, exercising any option, or requiring performance, shall be construed to be a waiver of that or any other right in connection with the Agreement.\n" +
                "No action arising out of this Agreement or your access to or use of our Platform, regardless of form or the basis of the claim, may be brought by you more than one (1) year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose) and you hereby waive any longer statute of limitations that may be permitted by law.\n" +
                "If My Virtual Vet, Inc. does take any legal action against you as a result of your violation of the Agreement, My Virtual Vet, Inc. will be entitled to recover from you, and you agree to pay, all reasonable attorneys’ fees and costs of such action, in addition to any other relief granted to My Virtual Vet, Inc.  You agree that My Virtual Vet, Inc. will not be liable to you or to any third party for termination of your access to, or use of, any of our Platform as a result of any violation of the Agreement or for any reason at all.\n" +
                "You may not assign, by operation of law or otherwise, any rights or delegate any duties under the Agreement to any third party without prior written consent by My Virtual Vet, Inc.  Any purported assignment lacking such consent will be void at its inception.  My Virtual Vet, Inc. may assign all or part of its rights and/or delegate all or part of its duties under the Agreement to any party, at any time, and in its sole discretion, upon notice of assignment by posting such notice on our Platform.");

    }
}